# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gon < Formula
  desc "Sign, notarize, and package macOS CLI applications written in any language."
  homepage ""
  version "0.2.9"
  depends_on :macos

  url "https://github.com/ConductorOne/gon/releases/download/v0.2.9/gon-darwin-amd64.zip"
  sha256 "1b34362abd1d092238c8120ca4c44a001f8df366ba465312546624fff22db97e"

  def install
    bin.install "gon"
  end

  if Hardware::CPU.arm?
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the Gon
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
