# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gon < Formula
  desc "Sign, notarize, and package macOS CLI applications written in any language."
  homepage ""
  version "0.2.7"
  depends_on :macos

  url "https://github.com/ConductorOne/gon/releases/download/v0.2.7/gon_Darwin_x86_64.zip"
  sha256 "fa3abee2bdec7b2eb5d8edbac0d453ca2dad83d0ea6f00bcbcee951e79736a64"

  def install
    bin.install "gon"
  end

  if Hardware::CPU.arm?
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the Gon
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
